#74
envirosolutionspl/pobieracz_danych_gugik pull request #100
Opened 2024-05-06 10:25 UTC by agluszek

2024-05-06 18:35 UTC, wojtek19022 requested changes
Tam brakuje mi tej weryfikacji ustawionej na false, tak jak to było wcześniej. Dodatkowo fajnie, że zrobiłaś timeouty. Na pewno ułatwi to w nieskończoność próbowanie pobrania tych paczek egib i może rozwiąże ten problem (jeszcze nie testowałem tej funkcjonalniści)

2024-05-06 18:41 UTC, wojtek19022 requested changes
I fajnie, że wyprintowałaś treść błędu, ale może to ubierzmy w lepszą formę, np. Jako pushMessage i level w zależności od treści błędu. Ew. Odłożenie w logach, ale skłaniałbym się ku pierwszemu

2024-05-09 07:51 UTC, agluszek commented
> I fajnie, że wyprintowałaś treść błędu, ale może to ubierzmy w lepszą formę, np. Jako pushMessage i level w zależności od treści błędu. Ew. Odłożenie w logach, ale skłaniałbym się ku pierwszemu

to akurat przez przypadek zostawiłam print, a to leci potem do pushMessage, wiec printa usunęłam

2024-05-09 11:28 UTC, wojtek19022 approved these changes
Git!

2024-05-09 11:39 UTC, merged