#96
envirosolutionspl/pobieracz_danych_gugik pull request #102
Opened 2024-05-06 10:27 UTC by agluszek

2024-05-06 16:10 UTC, wojtek19022 requested changes
Fajnie, że tutaj zrobiłaś brak weryfikacji requestów. Dodatkowo to pominięcie tych warningów też spoko działa. Jedyne co bym zmienił, to w niektórych miejscach zostało jeszcze użycie biblioteki requests. Tutaj byłbym za wprowadzeniem jednolicie już tych sesji na własnym certyfikacie SSL z tej funkcji get_legacy_session.

2024-05-06 16:10 UTC, wojtek19022 commented on tasks/downloadModel3dTask.py
Tutaj byłbym za wprowadzeniem jednolicie już tych sesji na własnym certyfikacie SSL z tej funkcji get_legacy_session

2024-05-06 16:10 UTC, wojtek19022 commented on tasks/downloadEgibExcelTask.py
Tutaj byłbym za wprowadzeniem jednolicie już tych sesji na własnym certyfikacie SSL z tej funkcji get_legacy_session

2024-05-06 16:10 UTC, wojtek19022 commented on tasks/downloadArchiwalnyBdotTask.py
Tutaj byłbym za wprowadzeniem jednolicie już tych sesji na własnym certyfikacie SSL z tej funkcji get_legacy_session

2024-05-06 16:10 UTC, wojtek19022 commented on service_api.py
Właściwie czemu usunęłaś tę sekcję finally?

2024-05-06 16:10 UTC, wojtek19022 commented on service_api.py
Fajnie że tutaj użyłaś tej funkcji z własnym certyfikatem ssl

2024-05-06 16:10 UTC, wojtek19022 commented on uldk.py
Fajnie że wyłączyłaś tutaj weryfikację w tych sesjach. Warto to powielać przy innych funkcjach w Pobieraczu

2024-05-06 16:10 UTC, wojtek19022 commented on wfs/utils.py
O super że uzyłaś get_legacy_session :) gut gut

2024-05-06 16:10 UTC, wojtek19022 commented on wms/utils.py
Tutaj bym też użył tej funkcji get_legacy_session

2024-05-06 16:10 UTC, wojtek19022 commented on wfs/wfs_egib.py
tutaj też bym użył legacy_session

2024-05-07 07:04 UTC, agluszek commented on service_api.py
usunęłam to po finally bo użycie with zastępuje close()

2024-05-07 19:51 UTC, wojtek19022 commented on tasks/downloadModel3dTask.py
O dobrze, że tutaj też ujednoliciłaś przypisanie tego url w DownloadModel3dTask :)

2024-05-07 19:54 UTC, wojtek19022 commented on uldk.py
O tutaj też spoko zrobiłaś z tymi gminami, województweami i powiatami :) tego bym się trzymał, dobra robota!

2024-05-07 19:57 UTC, wojtek19022 commented on wfs/utils.py
O też spoko że to przeniosłaś, bo faktycznie jak nie ma odpowiedzi to nie ma czego czytać wtyczka

2024-05-07 20:03 UTC, wojtek19022 commented on wms/utils.py
O tutaj też fajnie, że włożyłaś to do wyjątków. Gut gut :)

2024-05-07 20:11 UTC, wojtek19022 commented
@agluszek Dodaj tylko proszę w których commitach odnosiłaś się do #94, bo widziałem w niektórych nawiązanie do tego wątku

2024-05-07 20:12 UTC, wojtek19022 approved these changes
Super :) elegancko

2024-05-07 20:21 UTC, merged