#87 automatyczne pobieranie adresu wfs egib; usunięcie niepotrzebnych konstrukcji try except KeyError
envirosolutionspl/pobieracz_danych_gugik pull request #106
Opened 2024-05-09 09:52 UTC by agluszek

2024-05-09 10:52 UTC, wojtek19022 commented
Na początku przeraziłem się liczbą usuniętych wierszy, ale później przypomniałem sobie, że to były adresy wfs hahaha

2024-05-09 11:18 UTC, wojtek19022 requested changes

2024-05-09 11:18 UTC, wojtek19022 commented on egib_api.py
Hmm w sumie nie pomyślałem wczesniej, ale może być problem z tą biblioteką Beautiful Soup. Może lepiej przetworzyć to na którąś z wewnętrznych bibliotek QGIS

2024-05-09 11:18 UTC, wojtek19022 commented on pobieracz_danych_gugik.py
Na pewno dla województwa lubelskeigo i powiatu bialskiego wszystko działa bez tej konstrukcji? Raczej nie bez powodu było to zrobione, bo co powiat to inny serwis

2024-05-09 11:18 UTC, wojtek19022 commented on uldk.py
O cool!

2024-05-09 11:18 UTC, wojtek19022 commented on tasks/downloadWfsEgibTask.py
Dobrze, że zmieniłaś zmienną wfs na wfs_url. Ma większy sens

2024-05-09 11:18 UTC, wojtek19022 commented on egib_api.py
I czy sprawdzałaś czy nawet jak już mam zainstalowaną tą bibliotekę, to czy jak nie mam internetu przy pobieraniu tych wfs, to błąd zostanie obsłużony? W sensie, czy wyskoczy jakieś powiadomienie o błędu połączenia z internetem?

2024-05-09 12:28 UTC, agluszek commented on egib_api.py
kurcze w moim qgisie v. 3.34.4 Beautiful Soup jest „wbudowana"

2024-05-09 13:06 UTC, agluszek commented on egib_api.py
jak nie ma internetu to nie pojawia się komunikat, ponadto po pobraniu otwiera się folderu który tworzy się dla pobranych plików, na to jest inne issue i chyba ten folder powinien być usuwany gdy nic się nie pobierze

2024-05-09 13:19 UTC, agluszek commented on pobieracz_danych_gugik.py
jestem pewna, że to jakaś zamierzchłość - próba obejścia KeyErrora bo tam była pobierana wartość ze słownika zamiast za pomocą .get() to słownik[wartość]; a domyślnie wartości z comboboxów są puste; sprawdziłam to tylko powinnam jeszcze dodać zabezpieczenia typu pushWarning jak w przypadku pobierania EGIB

2024-05-09 15:03 UTC, wojtek19022 commented on egib_api.py
Tak, z tym folderem to ja się uporam bo to przyda się w każdej funkcji

2024-05-09 15:04 UTC, wojtek19022 commented on egib_api.py
To może pogadam z Jarkiem co do tego BS

2024-05-09 18:36 UTC, agluszek commented on egib_api.py
Na win na QGIS 3.22 nie ma tej biblioteki bs4, więc coś ogarnę innego, czy dodać komunikat kiedy nie ma połączenia?

2024-05-09 18:40 UTC, wojtek19022 commented on egib_api.py
Co do komunikatu to tak, jak najbardziej. A jakie masz plany właśnei na to zczytywanie? Ewentualnie jak się nie uda z wewnętrzną jakąś biblioteką qgis'a, to można zamiast z wewnątrz kodu pythona, to wrzucić jakiś plik tekstowy z tymi wfs'ami

2024-05-09 19:58 UTC, agluszek commented on egib_api.py
właśnie wrzuciłam commita z tym - zamieniłam na bibliotekę lxml

2024-05-09 20:00 UTC, agluszek commented on egib_api.py
to jeszcze dodam ten komunikat, ale to już jutro (:

2024-05-09 21:01 UTC, wojtek19022 commented on egib_api.py
> właśnie wrzuciłam commita z tym - zamieniłam na bibliotekę lxml

o myślałem że ona służy bardziej do obsługi XML

2024-05-10 06:12 UTC, agluszek commented on egib_api.py
dodałam komunikat kiedy przy tworzeniu słownika z WFSami nastąpi ConnectionError, dalej już przy pobieraniu konkretnego WFSa jest już ten błąd obsłużony

2024-05-10 06:29 UTC, agluszek commented on egib_api.py
> Tak, z tym folderem to ja się uporam bo to przyda się w każdej funkcji

to daj proszę znać czy bierzesz to całe issue 84 - bo miałam się za to zabierać

2024-05-10 06:57 UTC, wojtek19022 commented on egib_api.py
> > Tak, z tym folderem to ja się uporam bo to przyda się w każdej funkcji
> 
> to daj proszę znać czy bierzesz to całe issue 84 - bo miałam się za to zabierać

Spoko, ja to wezmę. Weź inne wątki

2024-05-10 06:59 UTC, wojtek19022 commented on egib_api.py
A bo trochę zrąbałem bo przypisałem go do Ciebie a miałem tym się sam zająć. To może zrobimy tak, ja wezmę ten wątek co się pojawił ostatnio, ten 105, a Ty weź 84

2024-05-10 07:40 UTC, agluszek commented on egib_api.py
oki

2024-05-11 22:46 UTC, wojtek19022 requested changes
Małe poprawki tylko bo w sumie fajnie działa

2024-05-11 22:46 UTC, wojtek19022 commented on egib_api.py
Dodaj tutaj Olu tylko timeout dla get_legacy_session w funkcji get_wfs_egib_dict bo nie pamiętam czy to zrobiłem wtedy w tym co Ci wysłałem

2024-05-11 22:46 UTC, wojtek19022 commented on pobieracz_danych_gugik.py
To jeszcze bym tylko prosił w tym pushMessage o zmianę duration na 10 i zrobię jeszcze osobny wątek na przejrzenie tego i żeby wszędzie były pushMessage z określonymi levelami i długością 10 sekund chyba że długość może być inna

2024-05-11 22:46 UTC, wojtek19022 commented on pobieracz_danych_gugik.py
Fajnie też że wstawiłaś ten błąd o nie wskazaniu obszaru! Tylko tak jak wyżej też bym go poprosił i będzie ideolo

2024-05-14 10:37 UTC, agluszek commented on egib_api.py
oki, dodane

2024-05-15 15:06 UTC, merged